# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\D\dev\Assolia\Dev_Git\QtUi_test\test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_test(object):
    def setupUi(self, MainWindow_test):
        MainWindow_test.setObjectName("MainWindow_test")
        MainWindow_test.resize(693, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow_test)
        self.centralwidget.setObjectName("centralwidget")
        self.Close_test = QtWidgets.QPushButton(self.centralwidget)
        self.Close_test.setGeometry(QtCore.QRect(530, 510, 75, 23))
        self.Close_test.setObjectName("Close_test")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.InputTab = QtWidgets.QWidget()
        self.InputTab.setObjectName("InputTab")
        self.ParcelCultureInputTable = QtWidgets.QTableWidget(self.InputTab)
        self.ParcelCultureInputTable.setGeometry(QtCore.QRect(0, 0, 162, 177))
        self.ParcelCultureInputTable.setRowCount(2)
        self.ParcelCultureInputTable.setColumnCount(1)
        self.ParcelCultureInputTable.setObjectName("ParcelCultureInputTable")
        self.ParcelCultureInputTable.horizontalHeader().setVisible(False)
        self.ParcelCultureInputTable.verticalHeader().setVisible(False)
        self.ValindInput = QtWidgets.QPushButton(self.InputTab)
        self.ValindInput.setGeometry(QtCore.QRect(500, 280, 75, 23))
        self.ValindInput.setObjectName("ValindInput")
        self.QttPailleMinText = QtWidgets.QPlainTextEdit(self.InputTab)
        self.QttPailleMinText.setGeometry(QtCore.QRect(0, 400, 150, 25))
        self.QttPailleMinText.setObjectName("QttPailleMinText")
        self.QttPailleMinBox = QtWidgets.QSpinBox(self.InputTab)
        self.QttPailleMinBox.setGeometry(QtCore.QRect(150, 400, 61, 25))
        self.QttPailleMinBox.setMaximum(9999999)
        self.QttPailleMinBox.setObjectName("QttPailleMinBox")
        self.QttEnsilageMinText = QtWidgets.QPlainTextEdit(self.InputTab)
        self.QttEnsilageMinText.setGeometry(QtCore.QRect(0, 425, 150, 25))
        self.QttEnsilageMinText.setObjectName("QttEnsilageMinText")
        self.QttEnsilageMinBox = QtWidgets.QSpinBox(self.InputTab)
        self.QttEnsilageMinBox.setGeometry(QtCore.QRect(150, 425, 61, 25))
        self.QttEnsilageMinBox.setMaximum(9999999)
        self.QttEnsilageMinBox.setObjectName("QttEnsilageMinBox")
        self.QttLuzerneMinText = QtWidgets.QPlainTextEdit(self.InputTab)
        self.QttLuzerneMinText.setGeometry(QtCore.QRect(0, 450, 150, 25))
        self.QttLuzerneMinText.setObjectName("QttLuzerneMinText")
        self.QttLuzerneMinBox = QtWidgets.QSpinBox(self.InputTab)
        self.QttLuzerneMinBox.setGeometry(QtCore.QRect(150, 450, 61, 25))
        self.QttLuzerneMinBox.setMaximum(9999999)
        self.QttLuzerneMinBox.setObjectName("QttLuzerneMinBox")
        self.tabWidget.addTab(self.InputTab, "")
        self.ConfigTab = QtWidgets.QWidget()
        self.ConfigTab.setObjectName("ConfigTab")
        self.ConfigCultureTypeTable = QtWidgets.QTableWidget(self.ConfigTab)
        self.ConfigCultureTypeTable.setGeometry(QtCore.QRect(0, 25, 452, 52))
        self.ConfigCultureTypeTable.setRowCount(1)
        self.ConfigCultureTypeTable.setColumnCount(2)
        self.ConfigCultureTypeTable.setObjectName("ConfigCultureTypeTable")
        self.ConfigCultureTypeTable.horizontalHeader().setVisible(False)
        self.ConfigCultureTypeTable.verticalHeader().setVisible(False)
        self.ConfigCultureTypeText = QtWidgets.QTextEdit(self.ConfigTab)
        self.ConfigCultureTypeText.setGeometry(QtCore.QRect(0, 0, 115, 25))
        self.ConfigCultureTypeText.setObjectName("ConfigCultureTypeText")
        self.NbYearSimulationBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbYearSimulationBox.setGeometry(QtCore.QRect(160, 390, 42, 25))
        self.NbYearSimulationBox.setObjectName("NbYearSimulationBox")
        self.NbYearSimulationText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbYearSimulationText.setGeometry(QtCore.QRect(0, 390, 160, 25))
        self.NbYearSimulationText.setObjectName("NbYearSimulationText")
        self.NbSimuPerYearText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbSimuPerYearText.setGeometry(QtCore.QRect(0, 415, 160, 25))
        self.NbSimuPerYearText.setObjectName("NbSimuPerYearText")
        self.NbSimuPerYearBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbSimuPerYearBox.setGeometry(QtCore.QRect(160, 415, 42, 25))
        self.NbSimuPerYearBox.setObjectName("NbSimuPerYearBox")
        self.ConfigSolTypeText = QtWidgets.QTextEdit(self.ConfigTab)
        self.ConfigSolTypeText.setGeometry(QtCore.QRect(0, 237, 115, 25))
        self.ConfigSolTypeText.setObjectName("ConfigSolTypeText")
        self.ConfigSolTypeTable = QtWidgets.QTableWidget(self.ConfigTab)
        self.ConfigSolTypeTable.setGeometry(QtCore.QRect(0, 262, 452, 27))
        self.ConfigSolTypeTable.setRowCount(1)
        self.ConfigSolTypeTable.setColumnCount(2)
        self.ConfigSolTypeTable.setObjectName("ConfigSolTypeTable")
        self.ConfigSolTypeTable.horizontalHeader().setVisible(False)
        self.ConfigSolTypeTable.verticalHeader().setVisible(False)
        self.NbBestResultText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbBestResultText.setGeometry(QtCore.QRect(0, 440, 160, 25))
        self.NbBestResultText.setObjectName("NbBestResultText")
        self.NbBestResultBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbBestResultBox.setGeometry(QtCore.QRect(160, 440, 42, 25))
        self.NbBestResultBox.setObjectName("NbBestResultBox")
        self.tabWidget.addTab(self.ConfigTab, "")
        self.OutputTab = QtWidgets.QWidget()
        self.OutputTab.setObjectName("OutputTab")
        self.OutputCultureTable = QtWidgets.QTableWidget(self.OutputTab)
        self.OutputCultureTable.setGeometry(QtCore.QRect(0, 0, 402, 177))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.OutputCultureTable.setFont(font)
        self.OutputCultureTable.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.OutputCultureTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.OutputCultureTable.setDragEnabled(True)
        self.OutputCultureTable.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.OutputCultureTable.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.OutputCultureTable.setRowCount(2)
        self.OutputCultureTable.setColumnCount(2)
        self.OutputCultureTable.setObjectName("OutputCultureTable")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OutputCultureTable.setItem(0, 0, item)
        self.OutputCultureTable.horizontalHeader().setVisible(False)
        self.OutputCultureTable.verticalHeader().setVisible(False)
        self.tableMarginConstraint = QtWidgets.QTableWidget(self.OutputTab)
        self.tableMarginConstraint.setGeometry(QtCore.QRect(0, 176, 402, 77))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tableMarginConstraint.setFont(font)
        self.tableMarginConstraint.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableMarginConstraint.setDragEnabled(True)
        self.tableMarginConstraint.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableMarginConstraint.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableMarginConstraint.setRowCount(2)
        self.tableMarginConstraint.setColumnCount(2)
        self.tableMarginConstraint.setObjectName("tableMarginConstraint")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMarginConstraint.setItem(0, 0, item)
        self.tableMarginConstraint.horizontalHeader().setVisible(False)
        self.tableMarginConstraint.verticalHeader().setVisible(False)
        self.IndexBestResultBox = QtWidgets.QSpinBox(self.OutputTab)
        self.IndexBestResultBox.setGeometry(QtCore.QRect(610, 10, 42, 25))
        self.IndexBestResultBox.setMaximum(4)
        self.IndexBestResultBox.setObjectName("IndexBestResultBox")
        self.IndexBestResultText = QtWidgets.QPlainTextEdit(self.OutputTab)
        self.IndexBestResultText.setGeometry(QtCore.QRect(540, 10, 70, 25))
        self.IndexBestResultText.setObjectName("IndexBestResultText")
        self.tabWidget.addTab(self.OutputTab, "")
        self.StartCalculation = QtWidgets.QPushButton(self.centralwidget)
        self.StartCalculation.setGeometry(QtCore.QRect(350, 510, 75, 23))
        self.StartCalculation.setObjectName("StartCalculation")
        MainWindow_test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow_test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_test)
        self.statusbar.setObjectName("statusbar")
        MainWindow_test.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow_test)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow_test)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_test)

    def retranslateUi(self, MainWindow_test):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_test.setWindowTitle(_translate("MainWindow_test", "MainWindow"))
        self.Close_test.setText(_translate("MainWindow_test", "Fermer"))
        self.ValindInput.setText(_translate("MainWindow_test", "Valider"))
        self.QttPailleMinText.setPlainText(_translate("MainWindow_test", "Quantité paille min"))
        self.QttEnsilageMinText.setPlainText(_translate("MainWindow_test", "Quantité ensilage min"))
        self.QttLuzerneMinText.setPlainText(_translate("MainWindow_test", "Quantité luzerne min"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputTab), _translate("MainWindow_test", "Entrées"))
        self.ConfigCultureTypeText.setHtml(_translate("MainWindow_test", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Types de cultures:</p></body></html>"))
        self.NbYearSimulationText.setPlainText(_translate("MainWindow_test", "Nombre d\'années simulées"))
        self.NbSimuPerYearText.setPlainText(_translate("MainWindow_test", "Nombre de simu par année"))
        self.ConfigSolTypeText.setHtml(_translate("MainWindow_test", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Types de sols:</p></body></html>"))
        self.NbBestResultText.setPlainText(_translate("MainWindow_test", "Nombre de résultats finaux"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConfigTab), _translate("MainWindow_test", "Configuration"))
        __sortingEnabled = self.OutputCultureTable.isSortingEnabled()
        self.OutputCultureTable.setSortingEnabled(False)
        self.OutputCultureTable.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tableMarginConstraint.isSortingEnabled()
        self.tableMarginConstraint.setSortingEnabled(False)
        self.tableMarginConstraint.setSortingEnabled(__sortingEnabled)
        self.IndexBestResultText.setPlainText(_translate("MainWindow_test", "Résultat n°"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OutputTab), _translate("MainWindow_test", "Résultats"))
        self.StartCalculation.setText(_translate("MainWindow_test", "Calculer"))
        self.menuFile.setTitle(_translate("MainWindow_test", "File"))
        self.actionExit.setText(_translate("MainWindow_test", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_test = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_test()
    ui.setupUi(MainWindow_test)
    MainWindow_test.show()
    sys.exit(app.exec_())
