# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\D\dev\Assolia\Dev_Git\QtUi_test\test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_test(object):
    def setupUi(self, MainWindow_test):
        MainWindow_test.setObjectName("MainWindow_test")
        MainWindow_test.resize(693, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow_test)
        self.centralwidget.setObjectName("centralwidget")
        self.Close_test = QtWidgets.QPushButton(self.centralwidget)
        self.Close_test.setGeometry(QtCore.QRect(440, 410, 75, 23))
        self.Close_test.setObjectName("Close_test")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 671, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.InputTab = QtWidgets.QWidget()
        self.InputTab.setObjectName("InputTab")
        self.ParcelCultureInputTable = QtWidgets.QTableWidget(self.InputTab)
        self.ParcelCultureInputTable.setGeometry(QtCore.QRect(0, 0, 162, 177))
        self.ParcelCultureInputTable.setRowCount(6)
        self.ParcelCultureInputTable.setColumnCount(2)
        self.ParcelCultureInputTable.setObjectName("ParcelCultureInputTable")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.ParcelCultureInputTable.setItem(0, 1, item)
        self.ParcelCultureInputTable.horizontalHeader().setVisible(False)
        self.ParcelCultureInputTable.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.InputTab, "")
        self.ConfigTab = QtWidgets.QWidget()
        self.ConfigTab.setObjectName("ConfigTab")
        self.ConfigCultureTypeTable = QtWidgets.QTableWidget(self.ConfigTab)
        self.ConfigCultureTypeTable.setGeometry(QtCore.QRect(0, 25, 452, 27))
        self.ConfigCultureTypeTable.setRowCount(1)
        self.ConfigCultureTypeTable.setColumnCount(5)
        self.ConfigCultureTypeTable.setObjectName("ConfigCultureTypeTable")
        self.ConfigCultureTypeTable.horizontalHeader().setVisible(False)
        self.ConfigCultureTypeTable.verticalHeader().setVisible(False)
        self.ConfigCultureTypeText = QtWidgets.QTextEdit(self.ConfigTab)
        self.ConfigCultureTypeText.setGeometry(QtCore.QRect(0, 0, 115, 25))
        self.ConfigCultureTypeText.setObjectName("ConfigCultureTypeText")
        self.NbYearSimulationBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbYearSimulationBox.setGeometry(QtCore.QRect(160, 310, 42, 25))
        self.NbYearSimulationBox.setObjectName("NbYearSimulationBox")
        self.NbYearSimulationText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbYearSimulationText.setGeometry(QtCore.QRect(0, 310, 160, 25))
        self.NbYearSimulationText.setObjectName("NbYearSimulationText")
        self.NbSimuPerYearText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbSimuPerYearText.setGeometry(QtCore.QRect(0, 335, 160, 25))
        self.NbSimuPerYearText.setObjectName("NbSimuPerYearText")
        self.NbSimuPerYearBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbSimuPerYearBox.setGeometry(QtCore.QRect(160, 335, 42, 25))
        self.NbSimuPerYearBox.setObjectName("NbSimuPerYearBox")
        self.ConfigCultureTypeText_2 = QtWidgets.QTextEdit(self.ConfigTab)
        self.ConfigCultureTypeText_2.setGeometry(QtCore.QRect(0, 75, 115, 25))
        self.ConfigCultureTypeText_2.setObjectName("ConfigCultureTypeText_2")
        self.ConfigCultureTypeTable_2 = QtWidgets.QTableWidget(self.ConfigTab)
        self.ConfigCultureTypeTable_2.setGeometry(QtCore.QRect(0, 100, 452, 27))
        self.ConfigCultureTypeTable_2.setRowCount(1)
        self.ConfigCultureTypeTable_2.setColumnCount(5)
        self.ConfigCultureTypeTable_2.setObjectName("ConfigCultureTypeTable_2")
        self.ConfigCultureTypeTable_2.horizontalHeader().setVisible(False)
        self.ConfigCultureTypeTable_2.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.ConfigTab, "")
        self.OutputTab = QtWidgets.QWidget()
        self.OutputTab.setObjectName("OutputTab")
        self.tableWidget = QtWidgets.QTableWidget(self.OutputTab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 402, 177))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tableWidget.setFont(font)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setRowCount(7)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableMarginConstraint = QtWidgets.QTableWidget(self.OutputTab)
        self.tableMarginConstraint.setGeometry(QtCore.QRect(0, 176, 402, 77))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tableMarginConstraint.setFont(font)
        self.tableMarginConstraint.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableMarginConstraint.setDragEnabled(True)
        self.tableMarginConstraint.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableMarginConstraint.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableMarginConstraint.setRowCount(3)
        self.tableMarginConstraint.setColumnCount(5)
        self.tableMarginConstraint.setObjectName("tableMarginConstraint")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMarginConstraint.setItem(0, 0, item)
        self.tableMarginConstraint.horizontalHeader().setVisible(False)
        self.tableMarginConstraint.verticalHeader().setVisible(False)
        self.IndexBestResultBox = QtWidgets.QSpinBox(self.OutputTab)
        self.IndexBestResultBox.setGeometry(QtCore.QRect(610, 10, 42, 25))
        self.IndexBestResultBox.setMaximum(4)
        self.IndexBestResultBox.setObjectName("IndexBestResultBox")
        self.IndexBestResultText = QtWidgets.QPlainTextEdit(self.OutputTab)
        self.IndexBestResultText.setGeometry(QtCore.QRect(540, 10, 70, 25))
        self.IndexBestResultText.setObjectName("IndexBestResultText")
        self.tabWidget.addTab(self.OutputTab, "")
        MainWindow_test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow_test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_test)
        self.statusbar.setObjectName("statusbar")
        MainWindow_test.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow_test)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow_test)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_test)

    def retranslateUi(self, MainWindow_test):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_test.setWindowTitle(_translate("MainWindow_test", "MainWindow"))
        self.Close_test.setText(_translate("MainWindow_test", "Fermer"))
        __sortingEnabled = self.ParcelCultureInputTable.isSortingEnabled()
        self.ParcelCultureInputTable.setSortingEnabled(False)
        self.ParcelCultureInputTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputTab), _translate("MainWindow_test", "Entrées"))
        self.ConfigCultureTypeText.setHtml(_translate("MainWindow_test", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Types de cultures:</p></body></html>"))
        self.NbYearSimulationText.setPlainText(_translate("MainWindow_test", "Nombre d\'années simulées"))
        self.NbSimuPerYearText.setPlainText(_translate("MainWindow_test", "Nombre de simu par année"))
        self.ConfigCultureTypeText_2.setHtml(_translate("MainWindow_test", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Types de sols:</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConfigTab), _translate("MainWindow_test", "Configuration"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tableMarginConstraint.isSortingEnabled()
        self.tableMarginConstraint.setSortingEnabled(False)
        self.tableMarginConstraint.setSortingEnabled(__sortingEnabled)
        self.IndexBestResultText.setPlainText(_translate("MainWindow_test", "Résultat n°"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OutputTab), _translate("MainWindow_test", "Résultats"))
        self.menuFile.setTitle(_translate("MainWindow_test", "File"))
        self.actionExit.setText(_translate("MainWindow_test", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_test = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_test()
    ui.setupUi(MainWindow_test)
    MainWindow_test.show()
    sys.exit(app.exec_())
