# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Assolia_Dev\Dev_Git\Git\QtUi_test\test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Assolia_MainWindow(object):
    def setupUi(self, Assolia_MainWindow):
        Assolia_MainWindow.setObjectName("Assolia_MainWindow")
        Assolia_MainWindow.resize(1000, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Assolia_Dev\\Dev_Git\\Git\\QtUi_test\\LogoAssolia_.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Assolia_MainWindow.setWindowIcon(icon)
        Assolia_MainWindow.setIconSize(QtCore.QSize(15, 50))
        self.centralwidget = QtWidgets.QWidget(Assolia_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Close_test = QtWidgets.QPushButton(self.centralwidget)
        self.Close_test.setGeometry(QtCore.QRect(530, 510, 75, 23))
        self.Close_test.setObjectName("Close_test")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 950, 501))
        self.tabWidget.setIconSize(QtCore.QSize(20, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.InputTab = QtWidgets.QWidget()
        self.InputTab.setObjectName("InputTab")
        self.ParcelCultureInputTable = QtWidgets.QTableWidget(self.InputTab)
        self.ParcelCultureInputTable.setGeometry(QtCore.QRect(0, 25, 162, 177))
        self.ParcelCultureInputTable.setRowCount(2)
        self.ParcelCultureInputTable.setColumnCount(1)
        self.ParcelCultureInputTable.setObjectName("ParcelCultureInputTable")
        self.ParcelCultureInputTable.horizontalHeader().setVisible(False)
        self.ParcelCultureInputTable.verticalHeader().setVisible(False)
        self.ValindInput = QtWidgets.QPushButton(self.InputTab)
        self.ValindInput.setGeometry(QtCore.QRect(470, 400, 75, 23))
        self.ValindInput.setObjectName("ValindInput")
        self.QttPailleMinText = QtWidgets.QPlainTextEdit(self.InputTab)
        self.QttPailleMinText.setGeometry(QtCore.QRect(0, 380, 150, 25))
        self.QttPailleMinText.setObjectName("QttPailleMinText")
        self.QttPailleMinBox = QtWidgets.QSpinBox(self.InputTab)
        self.QttPailleMinBox.setGeometry(QtCore.QRect(150, 380, 61, 25))
        self.QttPailleMinBox.setMaximum(9999999)
        self.QttPailleMinBox.setObjectName("QttPailleMinBox")
        self.QttEnsilageMinText = QtWidgets.QPlainTextEdit(self.InputTab)
        self.QttEnsilageMinText.setGeometry(QtCore.QRect(0, 405, 150, 25))
        self.QttEnsilageMinText.setObjectName("QttEnsilageMinText")
        self.QttEnsilageMinBox = QtWidgets.QSpinBox(self.InputTab)
        self.QttEnsilageMinBox.setGeometry(QtCore.QRect(150, 405, 61, 25))
        self.QttEnsilageMinBox.setMaximum(9999999)
        self.QttEnsilageMinBox.setObjectName("QttEnsilageMinBox")
        self.QttLuzerneMinText = QtWidgets.QPlainTextEdit(self.InputTab)
        self.QttLuzerneMinText.setGeometry(QtCore.QRect(0, 430, 150, 25))
        self.QttLuzerneMinText.setObjectName("QttLuzerneMinText")
        self.QttLuzerneMinBox = QtWidgets.QSpinBox(self.InputTab)
        self.QttLuzerneMinBox.setGeometry(QtCore.QRect(150, 430, 61, 25))
        self.QttLuzerneMinBox.setMaximum(9999999)
        self.QttLuzerneMinBox.setObjectName("QttLuzerneMinBox")
        self.UserNameText = QtWidgets.QPlainTextEdit(self.InputTab)
        self.UserNameText.setGeometry(QtCore.QRect(0, 0, 150, 25))
        self.UserNameText.setObjectName("UserNameText")
        self.UserNameComboBox = QtWidgets.QComboBox(self.InputTab)
        self.UserNameComboBox.setGeometry(QtCore.QRect(150, 0, 200, 25))
        self.UserNameComboBox.setObjectName("UserNameComboBox")
        self.tabWidget.addTab(self.InputTab, "")
        self.ConfigTab = QtWidgets.QWidget()
        self.ConfigTab.setObjectName("ConfigTab")
        self.ConfigCultureTypeTable = QtWidgets.QTableWidget(self.ConfigTab)
        self.ConfigCultureTypeTable.setGeometry(QtCore.QRect(0, 25, 452, 52))
        self.ConfigCultureTypeTable.setRowCount(1)
        self.ConfigCultureTypeTable.setColumnCount(2)
        self.ConfigCultureTypeTable.setObjectName("ConfigCultureTypeTable")
        self.ConfigCultureTypeTable.horizontalHeader().setVisible(False)
        self.ConfigCultureTypeTable.verticalHeader().setVisible(False)
        self.ConfigCultureTypeText = QtWidgets.QTextEdit(self.ConfigTab)
        self.ConfigCultureTypeText.setGeometry(QtCore.QRect(0, 0, 115, 25))
        self.ConfigCultureTypeText.setObjectName("ConfigCultureTypeText")
        self.NbYearSimulationBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbYearSimulationBox.setGeometry(QtCore.QRect(160, 390, 42, 25))
        self.NbYearSimulationBox.setObjectName("NbYearSimulationBox")
        self.NbYearSimulationText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbYearSimulationText.setGeometry(QtCore.QRect(0, 390, 160, 25))
        self.NbYearSimulationText.setObjectName("NbYearSimulationText")
        self.NbSimuPerYearText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbSimuPerYearText.setGeometry(QtCore.QRect(0, 415, 160, 25))
        self.NbSimuPerYearText.setObjectName("NbSimuPerYearText")
        self.NbSimuPerYearBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbSimuPerYearBox.setGeometry(QtCore.QRect(160, 415, 42, 25))
        self.NbSimuPerYearBox.setObjectName("NbSimuPerYearBox")
        self.ConfigSolTypeText = QtWidgets.QTextEdit(self.ConfigTab)
        self.ConfigSolTypeText.setGeometry(QtCore.QRect(0, 237, 115, 25))
        self.ConfigSolTypeText.setObjectName("ConfigSolTypeText")
        self.ConfigSolTypeTable = QtWidgets.QTableWidget(self.ConfigTab)
        self.ConfigSolTypeTable.setGeometry(QtCore.QRect(0, 262, 452, 27))
        self.ConfigSolTypeTable.setRowCount(1)
        self.ConfigSolTypeTable.setColumnCount(2)
        self.ConfigSolTypeTable.setObjectName("ConfigSolTypeTable")
        self.ConfigSolTypeTable.horizontalHeader().setVisible(False)
        self.ConfigSolTypeTable.verticalHeader().setVisible(False)
        self.NbBestResultText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbBestResultText.setGeometry(QtCore.QRect(0, 440, 160, 25))
        self.NbBestResultText.setObjectName("NbBestResultText")
        self.NbBestResultBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbBestResultBox.setEnabled(False)
        self.NbBestResultBox.setGeometry(QtCore.QRect(160, 440, 42, 25))
        self.NbBestResultBox.setObjectName("NbBestResultBox")
        self.NbYearLuzerneText = QtWidgets.QPlainTextEdit(self.ConfigTab)
        self.NbYearLuzerneText.setGeometry(QtCore.QRect(0, 330, 160, 25))
        self.NbYearLuzerneText.setObjectName("NbYearLuzerneText")
        self.NbYearLuzerneBox = QtWidgets.QSpinBox(self.ConfigTab)
        self.NbYearLuzerneBox.setGeometry(QtCore.QRect(160, 330, 42, 25))
        self.NbYearLuzerneBox.setMinimum(1)
        self.NbYearLuzerneBox.setMaximum(6)
        self.NbYearLuzerneBox.setProperty("value", 4)
        self.NbYearLuzerneBox.setObjectName("NbYearLuzerneBox")
        self.ConfigOptiGroup = QtWidgets.QGroupBox(self.ConfigTab)
        self.ConfigOptiGroup.setGeometry(QtCore.QRect(280, 360, 241, 51))
        self.ConfigOptiGroup.setObjectName("ConfigOptiGroup")
        self.ConfigOptiMB_Text = QtWidgets.QPlainTextEdit(self.ConfigOptiGroup)
        self.ConfigOptiMB_Text.setGeometry(QtCore.QRect(20, 20, 71, 25))
        self.ConfigOptiMB_Text.setObjectName("ConfigOptiMB_Text")
        self.ConfigOptiMbIft_Slider = QtWidgets.QSlider(self.ConfigOptiGroup)
        self.ConfigOptiMbIft_Slider.setGeometry(QtCore.QRect(100, 20, 81, 22))
        self.ConfigOptiMbIft_Slider.setMaximum(2)
        self.ConfigOptiMbIft_Slider.setProperty("value", 1)
        self.ConfigOptiMbIft_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.ConfigOptiMbIft_Slider.setObjectName("ConfigOptiMbIft_Slider")
        self.ConfigOptiIFT_Text = QtWidgets.QPlainTextEdit(self.ConfigOptiGroup)
        self.ConfigOptiIFT_Text.setGeometry(QtCore.QRect(190, 20, 41, 25))
        self.ConfigOptiIFT_Text.setObjectName("ConfigOptiIFT_Text")
        self.tabWidget.addTab(self.ConfigTab, "")
        self.HiddenConfigTab = QtWidgets.QWidget()
        self.HiddenConfigTab.setObjectName("HiddenConfigTab")
        self.ConfigCultureSolTable = QtWidgets.QTableWidget(self.HiddenConfigTab)
        self.ConfigCultureSolTable.setGeometry(QtCore.QRect(0, 25, 452, 52))
        self.ConfigCultureSolTable.setRowCount(1)
        self.ConfigCultureSolTable.setColumnCount(2)
        self.ConfigCultureSolTable.setObjectName("ConfigCultureSolTable")
        self.ConfigCultureSolTable.horizontalHeader().setVisible(False)
        self.ConfigCultureSolTable.verticalHeader().setVisible(False)
        self.ConfigCultureSolText = QtWidgets.QTextEdit(self.HiddenConfigTab)
        self.ConfigCultureSolText.setGeometry(QtCore.QRect(0, 0, 210, 25))
        self.ConfigCultureSolText.setObjectName("ConfigCultureSolText")
        self.ConfigRotationCultureN_1Text = QtWidgets.QTextEdit(self.HiddenConfigTab)
        self.ConfigRotationCultureN_1Text.setGeometry(QtCore.QRect(0, 210, 210, 25))
        self.ConfigRotationCultureN_1Text.setObjectName("ConfigRotationCultureN_1Text")
        self.ConfigRotationCultureN_1Table = QtWidgets.QTableWidget(self.HiddenConfigTab)
        self.ConfigRotationCultureN_1Table.setGeometry(QtCore.QRect(0, 235, 452, 52))
        self.ConfigRotationCultureN_1Table.setRowCount(1)
        self.ConfigRotationCultureN_1Table.setColumnCount(2)
        self.ConfigRotationCultureN_1Table.setObjectName("ConfigRotationCultureN_1Table")
        self.ConfigRotationCultureN_1Table.horizontalHeader().setVisible(False)
        self.ConfigRotationCultureN_1Table.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.HiddenConfigTab, "")
        self.OutputTab = QtWidgets.QWidget()
        self.OutputTab.setObjectName("OutputTab")
        self.OutputCultureTable = QtWidgets.QTableWidget(self.OutputTab)
        self.OutputCultureTable.setGeometry(QtCore.QRect(0, 25, 402, 177))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.OutputCultureTable.setFont(font)
        self.OutputCultureTable.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.OutputCultureTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.OutputCultureTable.setDragEnabled(True)
        self.OutputCultureTable.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.OutputCultureTable.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.OutputCultureTable.setRowCount(2)
        self.OutputCultureTable.setColumnCount(2)
        self.OutputCultureTable.setObjectName("OutputCultureTable")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.OutputCultureTable.setItem(0, 0, item)
        self.OutputCultureTable.horizontalHeader().setVisible(False)
        self.OutputCultureTable.verticalHeader().setVisible(False)
        self.tableMarginConstraint = QtWidgets.QTableWidget(self.OutputTab)
        self.tableMarginConstraint.setGeometry(QtCore.QRect(0, 210, 402, 77))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tableMarginConstraint.setFont(font)
        self.tableMarginConstraint.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableMarginConstraint.setDragEnabled(True)
        self.tableMarginConstraint.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableMarginConstraint.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableMarginConstraint.setRowCount(2)
        self.tableMarginConstraint.setColumnCount(2)
        self.tableMarginConstraint.setObjectName("tableMarginConstraint")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableMarginConstraint.setItem(0, 0, item)
        self.tableMarginConstraint.horizontalHeader().setVisible(False)
        self.tableMarginConstraint.verticalHeader().setVisible(False)
        self.IndexBestResultBox = QtWidgets.QSpinBox(self.OutputTab)
        self.IndexBestResultBox.setGeometry(QtCore.QRect(70, 0, 42, 25))
        self.IndexBestResultBox.setMaximum(4)
        self.IndexBestResultBox.setObjectName("IndexBestResultBox")
        self.IndexBestResultText = QtWidgets.QPlainTextEdit(self.OutputTab)
        self.IndexBestResultText.setGeometry(QtCore.QRect(0, 0, 70, 25))
        self.IndexBestResultText.setObjectName("IndexBestResultText")
        self.tabWidget.addTab(self.OutputTab, "")
        self.StartCalculation = QtWidgets.QPushButton(self.centralwidget)
        self.StartCalculation.setGeometry(QtCore.QRect(350, 510, 75, 23))
        self.StartCalculation.setObjectName("StartCalculation")
        Assolia_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Assolia_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Assolia_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Assolia_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Assolia_MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(Assolia_MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionParametre_administrateur = QtWidgets.QAction(Assolia_MainWindow)
        self.actionParametre_administrateur.setObjectName("actionParametre_administrateur")
        self.actionOuvrir = QtWidgets.QAction(Assolia_MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionEnregistrer = QtWidgets.QAction(Assolia_MainWindow)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionEnregistrer_sous = QtWidgets.QAction(Assolia_MainWindow)
        self.actionEnregistrer_sous.setObjectName("actionEnregistrer_sous")
        self.actionAbout = QtWidgets.QAction(Assolia_MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOuvrir)
        self.menuFile.addAction(self.actionEnregistrer)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionParametre_administrateur)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Assolia_MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Assolia_MainWindow)

    def retranslateUi(self, Assolia_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Assolia_MainWindow.setWindowTitle(_translate("Assolia_MainWindow", "Assolia V020"))
        self.Close_test.setText(_translate("Assolia_MainWindow", "Fermer"))
        self.ValindInput.setText(_translate("Assolia_MainWindow", "Valider"))
        self.QttPailleMinText.setPlainText(_translate("Assolia_MainWindow", "Quantité paille min"))
        self.QttEnsilageMinText.setPlainText(_translate("Assolia_MainWindow", "Quantité ensilage min"))
        self.QttLuzerneMinText.setPlainText(_translate("Assolia_MainWindow", "Quantité luzerne min"))
        self.UserNameText.setPlainText(_translate("Assolia_MainWindow", "Nom utilisateur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputTab), _translate("Assolia_MainWindow", "Entrées"))
        self.ConfigCultureTypeText.setHtml(_translate("Assolia_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Types de cultures:</p></body></html>"))
        self.NbYearSimulationText.setPlainText(_translate("Assolia_MainWindow", "Nombre d\'années simulées"))
        self.NbSimuPerYearText.setPlainText(_translate("Assolia_MainWindow", "Nombre de simu par année"))
        self.ConfigSolTypeText.setHtml(_translate("Assolia_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Types de sols:</p></body></html>"))
        self.NbBestResultText.setPlainText(_translate("Assolia_MainWindow", "Nombre de résultats finaux"))
        self.NbYearLuzerneText.setPlainText(_translate("Assolia_MainWindow", "Nombre d\'années luzerne"))
        self.ConfigOptiGroup.setTitle(_translate("Assolia_MainWindow", "Config optimisation Marge Brute / IFT"))
        self.ConfigOptiMB_Text.setPlainText(_translate("Assolia_MainWindow", "Marge Brute "))
        self.ConfigOptiIFT_Text.setPlainText(_translate("Assolia_MainWindow", "IFT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConfigTab), _translate("Assolia_MainWindow", "Configuration"))
        self.ConfigCultureSolText.setHtml(_translate("Assolia_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Impact du type de sol sur les cultures:</p></body></html>"))
        self.ConfigRotationCultureN_1Text.setHtml(_translate("Assolia_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Rotation (impact de n-1)</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HiddenConfigTab), _translate("Assolia_MainWindow", "Configuration cachée"))
        __sortingEnabled = self.OutputCultureTable.isSortingEnabled()
        self.OutputCultureTable.setSortingEnabled(False)
        self.OutputCultureTable.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tableMarginConstraint.isSortingEnabled()
        self.tableMarginConstraint.setSortingEnabled(False)
        self.tableMarginConstraint.setSortingEnabled(__sortingEnabled)
        self.IndexBestResultText.setPlainText(_translate("Assolia_MainWindow", "Résultat n°"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OutputTab), _translate("Assolia_MainWindow", "Résultats"))
        self.StartCalculation.setText(_translate("Assolia_MainWindow", "Calculer"))
        self.menuFile.setTitle(_translate("Assolia_MainWindow", "Fichier"))
        self.actionExit.setText(_translate("Assolia_MainWindow", "Fermer"))
        self.actionParametre_administrateur.setText(_translate("Assolia_MainWindow", "Parametre administrateur"))
        self.actionOuvrir.setText(_translate("Assolia_MainWindow", "Ouvrir ..."))
        self.actionEnregistrer.setText(_translate("Assolia_MainWindow", "Enregistrer"))
        self.actionEnregistrer_sous.setText(_translate("Assolia_MainWindow", "Enregistrer sous ..."))
        self.actionAbout.setText(_translate("Assolia_MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Assolia_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Assolia_MainWindow()
    ui.setupUi(Assolia_MainWindow)
    Assolia_MainWindow.show()
    sys.exit(app.exec_())
